# Mark Shust's Docker Configuration for Magento
# (https://github.com/markshust/docker-magento)
#
# Version 37.0.2

version: "3"

services:
  app:
    #extra_hosts:
    #  - host.docker.internal:gateway.docker.internal
    env_file: env/debug.env
    networks:
      erpnet:
        aliases:
          - magento.test
    volumes: &appvolumes
      # Host mounts with performance penalty, only put what is necessary here
      - ./src/app/code:/var/www/html/app/code:cached
      - ./src/app/design:/var/www/html/app/design:cached
      - ./src/app/etc:/var/www/html/app/etc:cached
      - ./src/composer.json:/var/www/html/composer.json:cached
      - ./src/composer.lock:/var/www/html/composer.lock:cached
      - ./src/nginx.conf.sample:/var/www/html/nginx.conf:cached
      - ./src/var/log:/var/www/html/var/log:cached
      - ./src/var/report:/var/www/html/var/report:cached
      - ../magento2-modules/beeapps-theme-merlu-basic:/var/www/html/app/design/frontend/Beeapps/theme-merlu-basic
      - ../magento2-modules/beeapps-m2-customer-addressbystore:/var/www/html/app/code/Beeapps/CustomerAddressByStore
      - ../magento2-modules/beeapps-m2-attributes-management:/var/www/html/app/code/Beeapps/AttributesManagement
      - ../magento2-modules/magento-module-custom-attribute-management:/var/www/html/app/code/Magento/CustomAttributeManagement
      - ../magento2-modules/magento-module-customer-custom-attributes:/var/www/html/app/code/Magento/CustomerCustomAttributes
      - ../magento2-modules/magento-ngrok:/var/www/html/app/code/Shkoliar/Ngrok
      #- ./src/auth.json:/var/www/html/auth.json:cached
      #- ./src/m2-hotfixes:/var/www/html/m2-hotfixes:cached
      #- ./src/patches:/var/www/html/patches:cached
      # To sync your SSH to the container, uncomment the following line:
      #- ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      # Linux only: remove the above lines and mount the entire src directory with:
      #- ./src:/var/www/html:cache

  ngrok:
    image: wernight/ngrok
    command: ngrok start base_app
    #entrypoint: /wrapper_entrypoint.sh
    extra_hosts:
      - "localhost:172.20.0.8"
    ports:
      - "4040:4040"
    depends_on:
      - app
    volumes:
      - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml:cached
      - ./ngrok_wrapper_entrypoint.sh:/wrapper_entrypoint.sh
      #- ssldata:/etc/nginx/certs:rw

  phpfpm:
    #extra_hosts:
    #  - host.docker.internal:gateway.docker.internal
    env_file: env/debug.env
    volumes: *appvolumes
    # Linux only: host.docker.internal doesn't exist https://github.com/docker/for-linux/issues/264
    # Uncomment two lines below & replace IP with result of: docker run --rm alpine ip route | awk 'NR==1 {print $3}'
    #extra_hosts:
    #  - "host.docker.internal:IP"
    #env_file: env/debug.env

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025"
      - "8025:8025"
    networks:
      - default
  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  volumes: *appvolumes
